/// Map of all possible emojis along with their names in [Category.SMILEYS]
final Map<String, String> smileys = new Map.fromIterables([
  'Grinning Face',
  'Grinning Face With Smiling Eyes',
  'Beaming Face With Smiling Eyes',
  'Grinning Face With Sweat',
  'Rolling on the Floor Laughing',
  'Face With Tears of Joy',
  'Slightly Smiling Face',
  'Winking Face',
  'Smiling Face With Hearts',
  'Smiling Face With Heart-Eyes',
  'Star-Struck',
  'Face Blowing a Kiss',
  'Face With Tongue',
  'Winking Face With Tongue',
  'Hugging Face',
  'Face With Hand Over Mouth',
  'Shushing Face',
  'Thinking Face',
  'Pensive Face',
  'Partying Face',
  'Smiling Face With Sunglasses',
  'Loudly Crying Face',
  'Face With Steam From Nose',
  'Pouting Face',
  'Face With Symbols on Mouth',
  'Smiling Face With Horns',
], [
  '😀',
  '😄',
  '😁',
  '😅',
  '🤣',
  '😂',
  '🙂',
  '😉',
  '🥰',
  '😍',
  '🤩',
  '😘',
  '😛',
  '😜',
  '🤗',
  '🤭',
  '🤫',
  '🤔',
  '😔',
  '🥳',
  '😎',
  '😭',
  '😤',
  '😡',
  '🤬',
  '😈',
]);

/// Map of all possible emojis along with their names in [Category.FOODS]
final Map<String, String> foods = new Map.fromIterables([
  'Watermelon',
  'Banana',
  'Red Apple',
  'Green Apple',
  'Peach',
  'Cherries',
  'Strawberry',
  'Kiwi Fruit',
  'Tomato',
  'Coconut',
  'Avocado',
  'Eggplant',
  'Carrot',
  'Ear of Corn',
  'Hamburger',
  'French Fries',
  'Pizza',
  'Hot Dog',
  'Doughnut',
  'Cookie',
  'Shortcake',
  'Cupcake',
  'Pie',
  'Chocolate Bar',
  'Candy',
  'Baby Bottle',
  'Hot Beverage',
  'Bottle With Popping Cork',
  'Cocktail Glass',
  'Tropical Drink',
  'Beer Mug',
  'Clinking Beer Mugs',
  'Clinking Glasses',
], [
  '🍉',
  '🍌',
  '🍎',
  '🍏',
  '🍑',
  '🍒',
  '🍓',
  '🥝',
  '🍅',
  '🥥',
  '🥑',
  '🍆',
  '🥕',
  '🌽',
  '🍔',
  '🍟',
  '🍕',
  '🌭',
  '🍩',
  '🍪',
  '🍰',
  '🧁',
  '🥧',
  '🍫',
  '🍬',
  '🍼',
  '☕',
  '🍾',
  '🍸',
  '🍹',
  '🍺',
  '🍻',
  '🥂',
]);

/// Map of all possible emojis along with their names in [Category.SYMBOLS]
final Map<String, String> symbols = new Map.fromIterables([
  'See-No-Evil Monkey',
  'Hear-No-Evil Monkey',
  'Speak-No-Evil Monkey',
  'Collision',
  'Dizzy',
  'Sweat Droplets',
  'Red Heart',
  'Orange Heart',
  'Yellow Heart',
  'Green Heart',
  'Blue Heart',
  'Purple Heart',
  'Black Heart',
  'Fire',
  'Hundred Points',
  'Anger Symbol',
  'Beach With Umbrella',
  'Man Surfing',
  'Woman Surfing',
  'Man Swimming',
  'Woman Swimming',
], [
  '🙈',
  '🙉',
  '🙊',
  '💥',
  '💫',
  '💦',
  '❤',
  '🧡',
  '💛',
  '💚',
  '💙',
  '💜',
  '🖤',
  '🔥',
  '💯',
  '💢',
  '🏖',
  '🏄\u200d♂️',
  '🏄\u200d♀️',
  '🏊\u200d♂️',
  '🏊\u200d♀️',
]);

/// Map of all possible emojis along with their names in [Category.FLAGS]
final Map<String, String> flags = new Map.fromIterables([
  'Flag: North Macedonia',
  'Flag: Serbia',
  'Flag: Slovenia',
  'Flag: Sweden',
  'Flag: Croatia',
  'Flag: Bosnia & Herzegovina',
  'Flag: England',
  'Flag: Papua New Guinea',
  'Flag: United States',
  'Flag: Zimbabwe',
], [
  '🇲🇰',
  '🇷🇸',
  '🇸🇮',
  '🇸🇪',
  '🇭🇷',
  '🇧🇦',
  '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  '🇵🇬',
  '🇺🇸',
  '🇿🇼',
]);
